[database]
path = "./prod-db.db3"

[manifold]
url = "https://manifold.markets/"
api_key = "SECRET"  # overridden by MB_MANIFOLD.API_KEY env variable
user_id = "PQ8Ot2GZ8NfQdXiJVmJqf3yea8O2"  # mirrorbot

[manifold.template]
description_footer = """\
    Once the original resolves, its resolution will be applied to this market \
    automatically. Trustworthy-ish users are encouraged to resolve this market \
    before then if the outcome is known and unambiguous.\
    """
title_retain_end_characters = 25 # keep the last 25 characters when truncating title
max_question_length = 120
max_description_length = 16000

[manifold.managrams]
min_amount = 10.0
mirror_cost = 50.0

[metaculus]
url = "https://www.metaculus.com/"
api_key = "SECRET"  # overridden by MB_METACULUS.API_KEY env variable
fetch_criteria = true  # when auto-mirroring, fetch resolution criteria for each question
max_clones_per_day = 10
add_group_ids = [
    "5mFuwp5QX0sdZYdNq3Jx", # Metaculus
]

[metaculus.auto_filter]
require_visible_community_prediction = true
require_open = true
exclude_resolved = true
exclude_grouped = true
min_forecasters = 25
min_votes = 0
min_days_to_resolution = 2
max_days_to_resolution = 4000
max_last_active_days = 7
max_age_days = 90
max_confidence = 0.97
exclude_ids = [18177, 18170, 18606, 18233, 18992, 18393, 18865]

[metaculus.request_filter]
require_visible_community_prediction = false
require_open = false
exclude_resolved = true
exclude_grouped = false
min_forecasters = 5
min_votes = 0
min_days_to_resolution = 1
max_days_to_resolution = 36525
max_last_active_days = 90
max_age_days = 36525
max_confidence = 0.97
exclude_ids = []

