[database]
path = "./dev-db.db3"

[kalshi]
max_clones_per_day = 1
add_group_ids = [
    "c7fb5859-6c37-4b10-be04-db8f218d80af", # Kalshi on dev
]

[kalshi.auto_filter]
require_open = true
exclude_resolved = true
exclude_series = true
min_liquidity = 0
min_volume = 0
min_recent_volume = 0
min_open_interest = 0
min_dollar_volume = 0
min_dollar_recent_volume = 0
min_dollar_open_interest = 0
min_days_to_resolution = 2
max_days_to_resolution = 4000
max_age_days = 365
max_confidence = 0.94
exclude_ids = []

[manifold]
url = "https://dev.manifold.markets/"
user_id = "Lx20DndIKqYBDrAdJz5geUeZnRz1"  # mirrorbot on dev

[metaculus]
fetch_criteria = true
max_clones_per_day = 10
add_group_ids = [
    # "4b65902d-5e43-4573-97af-1b10aac92daa"  # we do a little testing
]

[metaculus.auto_filter]
require_visible_community_prediction = true
require_open = true
exclude_resolved = true
exclude_grouped = true
min_forecasters = 30
min_votes = 0
min_days_to_resolution = 7
max_days_to_resolution = 666
max_last_active_days = 7
max_age_days = 60
max_confidence = 0.97

